# Generated by Django 4.0.3 on 2022-04-03 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_comment_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Ответ на коментарий "Родителя"', null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.comment', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='store.product', verbose_name='Продукт'),
        ),
    ]
