# Generated by Django 4.0.3 on 2022-04-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_comment_parent_alter_comment_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.JSONField(blank=True, null=True, verbose_name='Характеристики'),
        ),
    ]
