# Generated by Django 3.2 on 2022-03-31 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, unique=True, verbose_name='Категория')),
                ('description', models.TextField(max_length=255, verbose_name='Описание категории')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Товар')),
                ('description', models.TextField(max_length=850, verbose_name='О товаре')),
                ('price_at_moment', models.PositiveIntegerField(verbose_name='Цена в данный момент')),
                ('quantity', models.IntegerField(verbose_name='Количество товара')),
                ('discounted_price', models.PositiveIntegerField(verbose_name='Скидка')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год выпуска')),
                ('color', models.CharField(max_length=120, verbose_name='Цвет товара')),
                ('status', models.CharField(choices=[('Have', 'Товар в наличии'), ('Havent', 'Товар временно отсутвует')], default='Have', max_length=35, verbose_name='Статус товара')),
                ('created_ad', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')),
                ('update_ad', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('cat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
