# Generated by Django 4.0.2 on 2022-04-13 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1024)),
                ('attachments', models.FileField(upload_to='')),
                ('send', models.CharField(choices=[('SEND', 'Отправить'), ('Draft', 'Черновик')], max_length=255)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Писмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
