# Generated by Django 4.0.2 on 2022-04-13 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailingletters',
            old_name='send',
            new_name='is_send',
        ),
    ]
