# Generated by Django 4.0.2 on 2022-04-13 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendemail', '0002_rename_send_mailingletters_is_send'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingletters',
            name='users',
        ),
        migrations.AddField(
            model_name='mailingletters',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
