# Generated by Django 4.0.2 on 2022-04-13 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendemail', '0003_remove_mailingletters_users_mailingletters_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingletters',
            name='users',
        ),
        migrations.AddField(
            model_name='mailingletters',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
