# Generated by Django 4.0.2 on 2022-04-16 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sendemail', '0004_remove_mailingletters_users_mailingletters_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1024)),
                ('attachments', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Писмо от пользователя',
                'verbose_name_plural': 'Письма от пользвателей',
            },
        ),
    ]
