# Generated by Django 4.0.2 on 2022-04-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendemail', '0005_customerletters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerletters',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='mailingletters',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
