# Generated by Django 4.0.2 on 2022-04-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_products_alter_customer_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='related_cart', to='cart.CartProduct', verbose_name='Товар корзины'),
        ),
    ]
