# Generated by Django 4.0.3 on 2022-04-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_customer_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartproduct',
            old_name='user',
            new_name='owner',
        ),
    ]
