# Generated by Django 4.0.3 on 2022-04-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photo/avatar/%Y/%m/%d', verbose_name='Фото пользователя'),
        ),
    ]
