# Generated by Django 3.2 on 2022-03-26 15:41

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220314_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='avatars/defalt.jpg', null=True, upload_to='avatars', verbose_name='Аватарка пользователя'),
        ),
    ]
