# Generated by Django 3.2 on 2022-03-26 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_change_key',
            field=models.CharField(default='', max_length=100, verbose_name='Ключ смены пароля'),
        ),
    ]
