# Generated by Django 3.2 on 2022-03-29 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_password_change_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_change_key',
        ),
    ]
